sudo: false  # travis container-based infrastructure

language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - python setup.py install

# command to run tests
script:
  - vic_utils -h

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0b751ac59ea833728a02
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
